# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Python runtime
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install build dependencies and runtime dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       build-essential \
       gfortran \
    && pip install --no-cache-dir . \
    && apt-get remove -y build-essential gfortran \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*

# Default command: run MCP over stdio
CMD ["python", "main.py"]
